### ISSUE TITLE
Unable to Compile Thermostat Example for ESP 32 

### ISSUE THREAD

**Issue by samisarfraz** [m5stack/azure_iothub_arduino_lib_esp32#1]
I am trying to compile the code and getting error:

_Arduino: 1.8.5 (Windows 7), Board: "ESP32 Dev Module, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from C:\Users\Sami Sarfraz\Documents\Arduino\libraries\arduino_48756\src\AzureIoTHubMQTTClient.h:27:0,

                 from C:\Users\Sami Sarfraz\Documents\Arduino\libraries\arduino_48756\src\AzureIoTHubMQTTClient.cpp:5:

C:\Users\Sami Sarfraz\Documents\Arduino\libraries\arduino_48756\src\NtpClientLib.h:98:2: error: #error "Incorrect platform. Only ARDUINO and ESP8266 MCUs are valid."

 #error "Incorrect platform. Only ARDUINO and ESP8266 MCUs are valid."

  ^

C:\Users\Sami Sarfraz\Documents\Arduino\libraries\arduino_48756\src\AzureIoTHubMQTTClient.cpp:10:25: fatal error: ESP8266WiFi.h: No such file or directory

compilation terminated.

Multiple libraries were found for "AzureIoTHub.h"
 Used: C:\Users\Sami Sarfraz\Documents\Arduino\libraries\AzureIoTHub
 Not used: C:\Users\Sami Sarfraz\Documents\Arduino\libraries\arduino_791381
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Sami Sarfraz\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences._

-------------------------------------------------------------------------------------------------------------

I also cannot add library to Arduino IDE and get an error:

Arduino: 1.8.5 (Windows 7), Board: "ESP32 Dev Module, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

Specified folder/zip file does not contain a valid library
Specified folder/zip file does not contain a valid library
A subfolder of your sketchbook is not a valid library
A subfolder of your sketchbook is not a valid library

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
-----------------------------------------------------------------------------------------------------------------

**Comment by 0x1abin** [comment]
Hi, this repository is deprecated, please use https://github.com/VSChina/ESP32_AzureIoT_Arduino/tree/master

**Comment by samisarfraz** [comment]
Dear @0x1abin ,

I have 1st used your recommended library by VSChina but unfortunately all the people who are using this library are getting same issue of ESP 32 device rebooting and not making stable connection with Azure IoT Hub. it gets connected but after sometime it gets TLSIO / MQTT error SNTP and nobody is responding to resolve listed below error. 

I have noticed one amazing things that when i have used example of remote monitoring using DHT 22 temperature & humidity sensor, it works fine and makes a very stable connection with Azure Iot Hub and device doesn't reboot and i have kept your example running for more than 6 hours and noticed zero error but in your example their is no support of receiving messages from Azure iot hub to device so we can execute functions but if use azure iot hub to send message to device then i see on serial monitor on device an error rather a message (but it receives at device end but doesn't comprehend)

I feel their is very minor work need to be done to your recommended library of VSChia but unluckily their is no support to resolve.

Link: if issue: https://github.com/VSChina/ESP32_AzureIoT_Arduino/issues/5

_An error occurs in the two examples if the delay between messages of 5 minutes or more.

"start sending events.
Info: >>>IoTHubClient_LL_SendEventAsync accepted message for transmission to IoT Hub.

Error: Time:Wed Jun 20 12:41:38 2018 File:C:\Users\jorge\Documents\Arduino\libraries\azure_esp32\src\Esp32MQTTClient.cpp Func:SendEventOnce Line:316 Waiting for send confirmation, time is up 10003

Info: >>>Re-connect.

Info: >>>Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

Info: Initializing SNTP

assertion "Operating mode must not be set while SNTP client is running" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/apps/sntp/sntp.c", line 591, function: sntp_setoperatingmode
abort() was called at PC 0x400e01eb on core 1

Backtrace: 0x40087b34:0x3ffd53d0 0x40087c33:0x3ffd53f0 0x400e01eb:0x3ffd5410 0x400f23d9:0x3ffd5440 0x400d3a3e:0x3ffd5460 0x400d3a9a:0x3ffd5480 0x400d2b96:0x3ffd54a0 0x400d2e3e:0x3ffd54e0 0x400d2e75:0x3ffd5500 0x400d2f9b:0x3ffd5540 0x400d22c1:0x3ffd5560 0x4012da3c:0x3ffd5600

Rebooting..."_

-----------------------------------------------------------------------------------------------------------------
 Hope hear from you with some positive outcome :)

**Comment by 0x1abin** [comment]
Solving this problem is difficult for me, maybe you can try the IDF stable SDK.
https://github.com/espressif/esp-azure

**Comment by Zontex** [comment]
closing because the date, can open again if the issue still exists, seems to be solved.
